### ISSUE TITLE
bRPC下载地址改为https://brpc.apache.org/download前缀

### ISSUE THREAD

**Issue by serverglen** [apache/incubator-brpc-website#100]
目前的下载地址是：https://brpc.apache.org/docs/downloadbrpc/

**Comment by wasphin** [comment]
同时需要考虑对先前地址的兼容，毕竟已经对外提供了

**Comment by wasphin** [comment]
直接移到外面感觉左侧没点缀不好看...

![Screenshot from 2022-10-29 16-27-59](https://user-images.githubusercontent.com/1237906/198821930-31c5c812-c2fc-4fd3-b5f9-52c33809d5e4.png)

**Comment by Huixxi** [comment]
> 直接移到外面感觉左侧没点缀不好看...
> 
> ![Screenshot from 2022-10-29 16-27-59](https://user-images.githubusercontent.com/1237906/198821930-31c5c812-c2fc-4fd3-b5f9-52c33809d5e4.png)

是的，所以我之前又给放回去了。。

**Comment by serverglen** [comment]
要不保持现状

**Comment by wwbmmm** [comment]
可以将 /download 重定向到 /docs/downloadbrpc/ ？

**Comment by serverglen** [comment]
这个是可以，但不知道在docsy中怎么配置...

**Comment by serverglen** [comment]
已经可以跳转了，可以试试，hugo应该支持。
