### ISSUE TITLE
修正外部资源引用问题

### ISSUE THREAD

**Issue by wasphin** [apache/incubator-brpc-website#104]
Site Check For Podling: https://whimsy.apache.org/pods/project/brpc

```
$ git grep 'www.google-analytics.com'
themes/docsy/assets/vendor/bootstrap/site/_includes/header.html:37:<script async src='https://www.google-analytics.com/analytics.js'></script>
$ git grep cdnjs.cloudflare.com
themes/docsy/assets/vendor/bootstrap/_config.yml:58:  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
themes/docsy/assets/vendor/bootstrap/site/docs/4.1/examples/dashboard/index.html:272:    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
themes/docsy/layouts/partials/scripts.html:2:<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
$ git grep stackpath.bootstrapcdn.com
themes/docsy/assets/vendor/bootstrap/_config.yml:52:  css:              "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
themes/docsy/assets/vendor/bootstrap/_config.yml:54:  js:               "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
themes/docsy/layouts/partials/scripts.html:3:<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
```

都是使用的主题中默认带的链接, 需要检查修正.

**Comment by Huixxi** [comment]
> Site Check For Podling: https://whimsy.apache.org/pods/project/brpc
> 
> ```
> $ git grep 'www.google-analytics.com'
> themes/docsy/assets/vendor/bootstrap/site/_includes/header.html:37:<script async src='https://www.google-analytics.com/analytics.js'></script>
> $ git grep cdnjs.cloudflare.com
> themes/docsy/assets/vendor/bootstrap/_config.yml:58:  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
> themes/docsy/assets/vendor/bootstrap/site/docs/4.1/examples/dashboard/index.html:272:    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
> themes/docsy/layouts/partials/scripts.html:2:<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
> $ git grep stackpath.bootstrapcdn.com
> themes/docsy/assets/vendor/bootstrap/_config.yml:52:  css:              "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
> themes/docsy/assets/vendor/bootstrap/_config.yml:54:  js:               "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
> themes/docsy/layouts/partials/scripts.html:3:<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
> ```
> 
> 都是使用的主题中默认带的链接, 需要检查修正.

感觉可以参考https://github.com/apache/dubbo-website/tree/master/themes 这个来解决

**Comment by serverglen** [comment]
已修复，close
