### ISSUE TITLE
Does `more processes` describe incorrectly?

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-brpc-website#82]
In https://brpc.apache.org/docs/rpc-in-depth/threading-overview/#n1-threading-library :
```text
N:1 threading libraries perform as well as event-loop libraries and are also scaled by deploying more processes in general.
```
I think it should be adjusted as follows :
```text
N:1 threading libraries perform as well as event-loop libraries and are also scaled by using more threads in general.
```

**Comment by wwbmmm** [comment]
> using more threads

this can be `using more threads or more processes`

**Comment by dragon-zhang** [comment]
> > using more threads
> 
> this can be `using more threads or more processes`

ok

**Comment by serverglen** [comment]
Thank for your contribution
